[webservers]
web-1 ansible_host=158.160.107.186 fqdn=fhma2iae16m3lnmvnbj3.auto.internal ansible_user=ubuntu
web-2 ansible_host=158.160.102.193 fqdn=fhmihc0dtee9qki4b6d9.auto.internal ansible_user=ubuntu

[databases]
main ansible_host=84.252.131.46 fqdn=fhmft3mladf19qs5ee27.auto.internal ansible_user=ubuntu
replica ansible_host=51.250.0.48 fqdn=fhmkvftl67nin41daqru.auto.internal ansible_user=ubuntu

[storage]
storage ansible_host=158.160.97.27 fqdn=fhm144t5h7qnc368cos2.auto.internal ansible_user=ubuntu
