[webservers]
web-1 ansible_host=158.160.125.176 fqdn=fhmhp1udss4cic9a7oea.auto.internal ansible_user=ubuntu
web-2 ansible_host=89.169.129.7 fqdn=fhmg2sv85qu8h3jprkjn.auto.internal ansible_user=ubuntu

[databases]
main ansible_host=51.250.3.99 fqdn=fhm2rarq5nu0k6egjsfv.auto.internal ansible_user=ubuntu
replica ansible_host=158.160.105.198 fqdn=fhmp0neubsgnipk230a1.auto.internal ansible_user=ubuntu

[storage]
storage ansible_host=158.160.113.231 fqdn=fhmcm6ed4uph3g9tk4lm.auto.internal ansible_user=ubuntu
